export const items = [
  {
    id: 1,
    img: "./images/placadevideo.jpeg",
    title: "Product name A",
    brand: "evga",
    condition: "new",
    product: "graphiccard",
    sale: 30,
    freeship: true,
    price: 4500.0,
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis ex, error earum quidem magni dolorum delectus!",
  },
  {
    id: 2,
    img: "./images/placadevideo.jpeg",
    title: "Product name A",
    brand: "evga",
    condition: "new",
    product: "graphiccard",
    sale: 0,
    freeship: true,
    price: 4500.0,
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis ex, error earum quidem magni dolorum delectus!",
  },
  {
    id: 3,
    img: "./images/placadevideo.jpeg",
    title: "Product name A",
    brand: "evga",
    condition: "semi",
    product: "graphiccard",
    sale: 30,
    freeship: false,
    price: 4500.0,
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis ex, error earum quidem magni dolorum delectus!",
  },
  {
    id: 4,
    img: "./images/redragon.jpg",
    title: "Keyboard redragon",
    brand: "redragon",
    condition: "new",
    product: "keyboard",
    sale: 9,
    freeship: false,
    price: 530.0,
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis ex, error earum quidem magni dolorum delectus!",
  },
  {
    id: 5,
    img: "./images/redragon.jpg",
    title: "Keyboard redragon",
    brand: "redragon",
    condition: "semi",
    product: "keyboard",
    sale: 0,
    freeship: true,
    price: 480.0,
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis ex, error earum quidem magni dolorum delectus!",
  },
  {
    id: 6,
    img: "./images/redragon.jpg",
    title: "Keyboard redragon",
    brand: "redragon",
    condition: "new",
    product: "keyboard",
    sale: 0,
    freeship: false,
    price: 480.0,
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis ex, error earum quidem magni dolorum delectus!",
  },
  {
    id: 7,
    img: "./images/hyperx.jpg",
    title: "Headset Gamer Cloud Stinger Core",
    brand: "hyperx",
    condition: "semi",
    product: "headset",
    sale: 20,
    freeship: true,
    price: 281.99,
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis ex, error earum quidem magni dolorum delectus!",
  },
  {
    id: 8,
    img: "./images/hyperx.jpg",
    title: "Headset Gamer Cloud Stinger Core",
    brand: "hyperx",
    condition: "new",
    product: "headset",
    sale: 0,
    freeship: true,
    price: 281.99,
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis ex, error earum quidem magni dolorum delectus!",
  },
  {
    id: 9,
    img: "./images/hyperx.jpg",
    title: "Headset Gamer Cloud Stinger Core",
    brand: "hyperx",
    condition: "new",
    product: "headset",
    sale: 0,
    freeship: false,
    price: 281.99,
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis ex, error earum quidem magni dolorum delectus!",
  },

  {
    id: 10,
    img: "./images/Thewitcher.png",
    title: "The witcher 3 - Wild Hunt",
    brand: "other",
    condition: "new",
    product: "game",
    sale: 4,
    freeship: false,
    price: 124.99,
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis ex, error earum quidem magni dolorum delectus!",
  },
  {
    id: 11,
    img: "./images/Thewitcher.png",
    title: "The witcher 3 - Wild Hunt",
    brand: "other",
    condition: "new",
    product: "game",
    sale: 0,
    freeship: true,
    price: 124.99,
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis ex, error earum quidem magni dolorum delectus!",
  },
  {
    id: 12,
    img: "./images/Thewitcher.png",
    title: "The witcher 3 - Wild Hunt",
    brand: "other",
    condition: "semi",
    product: "game",
    sale: 0,
    freeship: false,
    price: 124.99,
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis ex, error earum quidem magni dolorum delectus!",
  },
];
